networks:
  internal-docker-network:
    name: internal-docker-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.11.0/24
          gateway: 172.28.11.1

services:
  hello-world-public:
    image: rancher/hello-world
    networks:
      - internal-docker-network
    labels:
      caddy: public.example.com # replace with your domain
      caddy.reverse_proxy: '{{upstreams 80}}'
  hello-world-private:
    image: rancher/hello-world
    networks:
      - internal-docker-network
    labels:
      caddy: private.example.com # replace with your domain
      caddy.0_import: with_sso
      caddy.reverse_proxy: '{{upstreams 80}}'
    # check out https://github.com/lucaslorentz/caddy-docker-proxy for labels documentation
  caddy:
    image: 'lucaslorentz/caddy-docker-proxy:2.9-alpine'
    restart: unless-stopped
    user: 1000:1000 # replace if you need to run as different user
    extra_hosts:
        - 'host.docker.internal:host-gateway'
    environment:
        - CADDY_DOCKER_POLLING_INTERVAL=5s
        - CADDY_DOCKER_CADDYFILE_PATH=/dynamic/Caddyfile
    networks:
        - internal-docker-network
    ports:
        - '80:80'
        - '443:443'
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock:ro' # make sure your user has access to docker.sock (:ro stands for read-only)
        - ./caddy/dynamic:/dynamic # add Caddyfile in caddy/dynamic
        - ./caddy/data:/data
        - ./caddy/config:/config
  oauth2-proxy:
    image: bitnami/oauth2-proxy:latest
    restart: unless-stopped
    user: 1000:1000 # replace if you need to run as different user
    command: --config /etc/oauth2/oauth2_proxy.cfg --upstream=static://202
    volumes:
        - ./oauth2-proxy:/etc/oauth2 # add emails.cfg and oauth2_proxy.cfg in oauth2-proxy
    networks:
        - internal-docker-network
    labels:
        caddy: sso.example.com # replace with your domain
        caddy.reverse_proxy: '{{upstreams 4180}}'
    # check https://github.com/lucaslorentz/caddy-docker-proxy for labels documentation